config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :articles do
    get 'suggestion', on: :collection
    resources :comments
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  def self.suggestion(indice)
    where(['title LIKE ?', "%#{indice}%"])
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: '123', password: '123', except: [:index, :show, :suggestion]
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.search(params[:search])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
      end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def suggestion
    @suggestion = Article.suggestion(params[:query]).select(:title, :id)
    render :json => { "suggestions": @suggestion }
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: '123', password: '123', only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
    end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_later
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:avatar, :name, :email, :login)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited
        this article from being saved:
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title
  %p
    = f.label :text
    %br/
    = f.text_area :text
  %p
    = f.submit

app/views/articles/edit.html.haml
%h1 Editing article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/index.html.haml
= render 'search/search'

%h1 Listing articles
= link_to 'New article', new_article_path
%table{:border => "1"}
  %tr
    %th Title
    %th Text
    %th{:colspan => "3"} Operation
  - @articles.each do |article|
    %tr
      %td= article.title
      %td= article.text
      %td= link_to 'Show', article_path(article)
      %td= link_to 'Edit', edit_article_path(article)
      %td= link_to 'Destroy', article_path(article),           |
          method: :delete, data: { confirm: 'Are you sure?' } |
= link_to 'Back', controller:'welcome'

app/views/articles/new.html.haml
%h1 New article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p
  %strong Title:
  = @article.title
%p
  %strong Text:
  = @article.text
%h3 Comments
= render @article.comments
%h4 Add a comment:
= render "comments/form"
= link_to 'Back', articles_path
| #{link_to 'Edit', edit_article_path(@article)}

app/views/comments/_comment.html.haml
%p
  %strong Commenter:
  = comment.commenter
%p
  %strong Comment:
  = comment.body
%p
  = link_to 'Destroy Comment', [comment.article, comment], |
    method: :delete,                                       |
    data: { confirm: 'Are you sure?' }                     |

app/views/comments/_form.html.haml
= form_for([@article, @article.comments.build]) do |f|
  %p
    = f.label :commenter
    %br/
    = f.text_field :commenter
  %p
    = f.label :body
    %br/
    = f.text_area :body
  %p
    = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/search/_search.html.haml
= form_for '', method: :get do
    = text_field_tag :search, params[:search]
    = submit_tag "Search", class: "btn btn-default"

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field= f.file_field :avatar
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :login
    = f.text_field :login
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

= link_to 'New User', new_user_path
%table
  %thead
    %tr
      %th Avatar
      %th Name
      %th Email
      %th Login
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= image_tag user.avatar(:thumb)
        %td= user.name
        %td= user.email
        %td= user.login
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Back', controller: 'welcome'

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  =image_tag @user.avatar.url
  %br
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Login:
  = @user.login

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/welcome/index.html.haml
%head
  :css
    #content{
    	position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: auto;
        height: 300px;
        width: 70%;
    	}
%body
  #content{:style => "text-align:center"}
    %h1 Welcome to the xxx Blog
    %h2
      This is the home page for the sample application.
    = link_to 'Artilces', controller: 'articles'
    = link_to 'Users', controller: 'users'